### ISSUE TITLE
Used Argument

### ISSUE THREAD

**Issue by GshamaB** [shdam/pairedGSEA#3]
Hi
I am trying to rerun the commands in readMe file. I am getting the following error
"Error in plot_ora(ora, paired = TRUE) : unused argument (paired = TRUE)" while running 
"plot_ora(ora, paired = TRUE) +
  ggplot2::theme_classic()" line

Thanks

**Comment by shdam** [comment]
Dear GshamaB,

Thank you for trying out `pairedGSEA` and raising the issue!

I should've foreseen this problem, so thanks for making me aware. 
It is likely because you are using the main Bioconductor version, which is not yet updated. 

You can update the package from the devel branch on Bioconductor: `BiocManager::install("pairedGSEA", version = "devel")` or install from GitHub: `remotes::install_github("shdam/pairedGSEA")`. Whichever you prefer, they are identical.

Hope this was helpful :)

Best regards,
Søren

**Comment by GshamaB** [comment]
Hey Soren,
Even after updating the package using BiocManager::install("pairedGSEA", version = "devel"), the same issue persist :(

**Comment by GshamaB** [comment]
Could you please let me know the version that was used for this package. Currently I am using the following versions
"Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)"

**Comment by shdam** [comment]
Hi Gayathri, 

Sorry to hear it is still acting up.

Hmm, that is weird.
I assume you did, but to be sure, remember to restart R after reinstalling the package :)

Your versions are fine. Could you check that you have pairedGSEA version 1.1.0 installed?

Best regards,
Søren

**Comment by GshamaB** [comment]
Hi Søren,

BRAVO!!!
You are right. pairedGSEA version 1.0.0 was installed which was not
compatible with Bioconductor 3.18. This time I installed pairedGSEA
(version 1.1.0) from github because in bioconductor version 1.0.0 of
pairedGSEA is only available.


*Best Regards,*
*Gayathri S*
*ICMR-SRF*
*Department of Biotechnology,*
*Third Floor, Academic Block 2,*

*Manipal Institute of Technology,*
*Udupi-Karkala Highway, Eshwarnagar*
*Manipal, Udupi - 576104, Karnataka*
*Phone*: +91-7019298280
*E-Mail*: ***@***.***

**Comment by GshamaB** [comment]
Hi Søren
Biocondutor has 1.0.0 version of pairedGSEA which is not compatible with main bioconductor version 3.18. Hence, I installed pairedGSEA version 1.1.0 from github. BRAVO!! its working

**Comment by shdam** [comment]
Very glad to hear it worked out :)
Hope you find the package helpful.
